### ISSUE TITLE
db writes synchronously on every request. 

### ISSUE THREAD

**Issue by brian-davis** [BaseSecrete/active_analytics#8]
The `.record_request` method will write to the database on [every request](https://github.com/BaseSecrete/active_analytics/blob/master/lib/active_analytics.rb#L16).  This could be a performance issue, and will only get worse as this table grows.

I've made a branch which moves this function [to a background job](https://github.com/BaseSecrete/active_analytics/compare/master...brian-davis:active_analytics:async?expand=1).

Maybe this is too big of a change or takes things in a different direction that you are thinking.  If not, let me know, and I'll open an actual pull request.

**Comment by alexisbernard** [comment]
Hi, thanks for sharing you changes. Yes, it slows down each request a little bit. However the main issue is to write to the database for each request even if the task is delayed in the background. If you have 1000 req/s you still have 1000 inserts or updates per seconds into the database. That is very annoying because it can saturate the database.

I have in mind to store the data in Redis for a short period of time. That is very fast. Then, a task will periodically transfer those data from Redis to the database. Thus there will be a lot less write queries than requests and the workload for the database will be lowered.
